#ifndef StTRIGGERS_H
#define StTRIGGERS_H

// see prescale.cxx 
enum trgNumbers{VPDMB_NOBSMD,VPDMB,BBCMB,HT0VPDMB,HT1VPDMB,HT2,HT0BBCMBTOF0,HT1BBCMBTOF0,HT2BBCMB,JP0,JP1,JP2,AJP,BBCMBTOF0,TOFMULT3VPD,TOFMULT4};
//enum trgNumbers{VPDMB,BBCMB,HT0VPDMB,HT1VPDMB,HT2,HT0BBCMBTOF0,HT1BBCMBTOF0,HT2BBCMB,BBCMBTOF0};

#endif
