void DrawPt2D(){
    gROOT->ProcessLine(".x ~/myStyle.C");  
    TGaxis::SetMaxDigits(3); 
    int const numPtBins=9;
    double binning[numPtBins+1]={0.6,1,1.2,1.5,2.0,2.5,3.5,4.5,5.5,8.5};   
    TFile *f = new TFile("./root/DCA_plots_Hijing_GammaConv.root");
    dr =(TH2F*)f->Get("pt2D_eh_pi01");
    dr->SetName("dr");
    TFile *f1 = new TFile("./root/DCA_plots_Hijing.root");
    er =(TH2F*)f1->Get("pt2D_eh_pi0");
    er->SetName("er");

    dr->GetXaxis()->SetRangeUser(binning[0],binning[1]);
    dr_1 =(TH1F*) dr->ProjectionY();
    dr_1->SetName("dr_1");
    dr->GetXaxis()->SetRangeUser(binning[1],binning[2]);
    dr_2 =(TH1F*) dr->ProjectionY();
    dr_2->SetName("dr_2");
    dr->GetXaxis()->SetRangeUser(binning[2],binning[3]);
    dr_3 =(TH1F*) dr->ProjectionY();
    dr_3->SetName("dr_3");
    dr->GetXaxis()->SetRangeUser(binning[3],binning[4]);
    dr_4 =(TH1F*) dr->ProjectionY();
    dr_4->SetName("dr_4");
    dr->GetXaxis()->SetRangeUser(binning[4],binning[5]);   
    dr_5 =(TH1F*) dr->ProjectionY();
    dr_5->SetName("dr_5");
    dr->GetXaxis()->SetRangeUser(binning[5],binning[6]); 
    dr_6 =(TH1F*) dr->ProjectionY();
    dr_6->SetName("dr_6");
    dr->GetXaxis()->SetRangeUser(binning[6],binning[7]);
    dr_7 =(TH1F*) dr->ProjectionY();
    dr_7->SetName("dr_7");
    dr->GetXaxis()->SetRangeUser(binning[7],binning[8]);
    dr_8 =(TH1F*) dr->ProjectionY();
    dr_8->SetName("dr_8");  
    dr->GetXaxis()->SetRangeUser(binning[8],binning[9]);
    dr_9 =(TH1F*) dr->ProjectionY();
    dr_9->SetName("dr_9");
    
    er->GetXaxis()->SetRangeUser(binning[0],binning[1]);
    er_1 =(TH1F*) er->ProjectionY();
    er_1->SetName("er_1");
    er->GetXaxis()->SetRangeUser(binning[1],binning[2]);
    er_2 =(TH1F*) er->ProjectionY();
    er_2->SetName("er_2");
    er->GetXaxis()->SetRangeUser(binning[2],binning[3]);
    er_3 =(TH1F*) er->ProjectionY();
    er_3->SetName("er_3");
    er->GetXaxis()->SetRangeUser(binning[3],binning[4]);
    er_4 =(TH1F*) er->ProjectionY();
    er_4->SetName("er_4");
    er->GetXaxis()->SetRangeUser(binning[4],binning[5]);   
    er_5 =(TH1F*) er->ProjectionY();
    er_5->SetName("er_5");
    er->GetXaxis()->SetRangeUser(binning[5],binning[6]); 
    er_6 =(TH1F*) er->ProjectionY();
    er_6->SetName("er_6");
    er->GetXaxis()->SetRangeUser(binning[6],binning[7]);
    er_7 =(TH1F*) er->ProjectionY();
    er_7->SetName("er_7");
    er->GetXaxis()->SetRangeUser(binning[7],binning[8]);
    er_8 =(TH1F*) er->ProjectionY();
    er_8->SetName("er_8");  
    er->GetXaxis()->SetRangeUser(binning[8],binning[9]);
    er_9 =(TH1F*) er->ProjectionY();
    er_9->SetName("er_9");

    
    dr_1->SetLineColor(kBlue-4);
    dr_2->SetLineColor(kBlue-7);
    dr_3->SetLineColor(kBlue-9);
    dr_4->SetLineColor(kRed-10);
    dr_5->SetLineColor(kRed-9);
    dr_6->SetLineColor(kRed-7);
    dr_7->SetLineColor(kRed-4);
    dr_8->SetLineColor(kRed+2);
    dr_9->SetLineColor(kPink-3);


    norm5(dr_1);   
    norm5(dr_2);   
    norm5(dr_3);
    norm5(dr_4);
    norm5(dr_5);
    norm5(dr_6); 
    norm5(dr_7);
    norm5(dr_8);
    norm5(dr_9);
 
    er_1->SetLineColor(kBlue-4);
    er_2->SetLineColor(kBlue-7);
    er_3->SetLineColor(kBlue-9);
    er_4->SetLineColor(kRed-10);
    er_5->SetLineColor(kRed-9);
    er_6->SetLineColor(kRed-7);
    er_7->SetLineColor(kRed-4);
    er_8->SetLineColor(kRed+2);
    er_9->SetLineColor(kPink-3);


    norm5(er_1);   
    norm5(er_2);   
    norm5(er_3);
    norm5(er_4);
    norm5(er_5);
    norm5(er_6); 
    norm5(er_7);
    norm5(er_8);
    norm5(er_9);

    TLegend *leg = new TLegend(0.4,0.74,0.6,0.9);
    TLegend *leg1 = new TLegend(0.2,0.7,0.4,0.9);
    leg1->AddEntry(dr_1,"p_{T}#in[0.6,1.0]","l");
    leg1->AddEntry(dr_2,"p_{T}#in[1.0,1.2]","l");
    leg1->AddEntry(dr_3,"p_{T}#in[1.2,1.5]","l");
    leg1->AddEntry(dr_4,"p_{T}#in[1.5,2.0]","l");
    leg1->AddEntry(dr_5,"p_{T}#in[2.0,2.5]","l");
    leg->AddEntry(dr_6,"p_{T}#in[2.5,3.5]","l");
    leg->AddEntry(dr_7,"p_{T}#in[3.5,4.5]","l");
    leg->AddEntry(dr_8,"p_{T}#in[4.5,5.5]","l");
    leg->AddEntry(dr_9,"p_{T}#in[4.5,8.5]","l");
    TCanvas *c11 = new TCanvas ("c11","");
    dr->GetXaxis()->SetRangeUser(0,10);
    dr->Draw("COLZ");
    TCanvas *c1 = new TCanvas ("c1","");
    //c1->cd(1);
    dr_1->Draw("hist same");
    //c1->cd(2);
    dr_2->Draw("hist same");
    //c1->cd(3);
    dr_3->Draw("hist same"); 
    //c1->cd(4);
    dr_4->Draw("hist same");
    //c1->cd(5);
    dr_5->Draw("hist same");
    //c1->cd(6);
    dr_6->Draw("hist same");
    //c1->cd(7);
    dr_7->Draw("hist same");
    //c1->cd(8);
    dr_8->Draw("hist same");
    //c1->cd(9);
    dr_9->Draw("hist same");
    er_1->Draw("PE same");
    //c1->cd(2);
    er_2->Draw("PE same");
    //c1->cd(3);
    er_3->Draw("PE same"); 
    //c1->cd(4);
    er_4->Draw("PE same");
    //c1->cd(5);
    er_5->Draw("PE same");
    //c1->cd(6);
    er_6->Draw("PE same");
    //c1->cd(7);
    er_7->Draw("PE same");
    //c1->cd(8);
    er_8->Draw("PE same");
    //c1->cd(9);
    er_9->Draw("PE same");
    leg->Draw("same");
    leg1->Draw("same");
}
void norm5(TH1F *h){
    h->GetXaxis()->SetTitle("#it{p}_{T} [GeV]");
    h->GetYaxis()->SetTitle("Arb. Units");
    h->GetYaxis()->SetRangeUser(1e-7,1);
    h->Rebin();
    double norm1 = h->Integral();
    int bins = h->GetNbinsX();
    for(int i=1; i<bins+1;i++){
	double temp = h->GetBinContent(i);
	double width = h->GetBinWidth(i);
	double err = h->GetBinError(i);
	h->SetBinContent(i,temp/norm1);
	h->SetBinError(i,err/norm1);
    }
}
