/// \file
/// \ingroup tutorial_tree
/// \notebook -nodraw
/// This example is a variant of hsimple.C but using a TTree instead
/// of a TNtuple. It shows:
///   - how to fill a Tree with a few simple variables.
///   - how to read this Tree
///   - how to browse and analyze the Tree via the TBrowser and TTreeViewer
/// This example can be run in many different ways:
///   1. Using the Cling interpreter
/// ~~~
/// .x tree1.C
/// ~~~
///   2. Using the automatic compiler interface
/// ~~~
/// .x tree1.C++
/// ~~~
///   3. 
/// ~~~
/// .L tree1.C  or .L tree1.C++
/// tree1()
/// ~~~
/// One can also run the write and read parts in two separate sessions.
/// For example following one of the sessions above, one can start the session:
/// ~~~
///   .L tree1.C
///   tree1r();
/// ~~~
/// \macro_code
///
/// \author Rene Brun

#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TRandom.h"

void tree1()
{
   //read the Tree generated by tree1w and fill two histograms

   //note that we use "new" to create the TFile and TTree objects !
   //because we want to keep these objects alive when we leave this function.
   TFile *f = new TFile("/Volumes/YJMAC/Matt_production/NPE_Tuples_Central5.root");
   TTree *t1 = (TTree*)f->Get("PhoE_M");
   Float_t beta;
   t1->SetBranchAddress("probe_beta",&beta);

   //create two histograms
   TH1F *hbeta   = new TH1F("hbeta","px distribution",500,-0.5,1);

   //read all entries and fill the histograms
   int num = 0;
   Long64_t nentries = t1->GetEntries();
   for (Long64_t i=0;i<nentries;i++) {
     t1->GetEntry(i);
     if(!beta) num++;
     hbeta->Fill(beta);
  }
 cout<<num<<endl;

  //we do not close the file. We want to keep the generated histograms
  //we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  new TBrowser();
  t1->StartViewer();
  hbeta->Draw();
  // in the browser, click on "ROOT Files", then on "tree1.root".
  //     you can click on the histogram icons in the right panel to draw them.
  // in the TreeViewer, follow the instructions in the Help button.
}

