root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"default\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"pileup\",kTRUE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"purity\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"rec\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"gpt\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"gpt04\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"masscut\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"nsigmae\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"poe\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"trig\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"fitrange\",kFALSE,kFALSE,kTRUE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"pythia\",kFALSE,kTRUE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep19\",\"jpsi\",kFALSE,kTRUE,kFALSE,kFALSE,kTRUE\)

