#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"default\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"pileup\",kTRUE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"purity\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"rec\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"gpt\",kFALSE,kFALSE,kFALSE,kFALSE\)
##root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"gpt04\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"masscut\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"nsigmae\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"poe\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"trig\",kFALSE,kFALSE,kFALSE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"fitrange\",kFALSE,kFALSE,kTRUE,kFALSE\)
#root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"pythia\",kFALSE,kTRUE,kFALSE,kFALSE\)
##root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"jpsi\",kFALSE,kTRUE,kFALSE,kFALSE,kTRUE\)

# do oneparamter fit for gpt, etc
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"pileup\",kTRUE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"purity\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"rec\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"gpt\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"masscut\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"nsigmae\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"poe\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"trig\",kFALSE,kFALSE,kFALSE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"fitrange\",kFALSE,kFALSE,kTRUE,kFALSE,kTRUE\)
root -b -q -l  systematicsMinuit.C\(\"Sep16\",\"pythia\",kFALSE,kTRUE,kFALSE,kFALSE,kTRUE\)
