#ifndef StMyAnalysisMaker_h
#define StMyAnalysisMaker_h
#include "StMaker.h"
#include <vector>
#include <map>
#ifndef ST_NO_NAMESPACES
using std::vector;
#endif
class StPicoDst;
class StPicoTrack;
class StPicoEvent;
class StPicoDstMaker;
class StPicoBEmcPidTraits;
class StPicoEmcTrigger;
class StPicoPhysicalHelix;

class TString;
class TH1F;
class TH2F;
class TH3F;
class TVector3;
class TFile;
#if !defined(ST_NO_TEMPLATE_DEF_ARGS) || defined(__CINT__)
typedef vector<int> IntVec;
typedef vector<Double_t> DoubleVec;
#else
typedef vector<int, allocator<int>> IntVec;
typedef vector<Double_t, allocator<Double_t>> DoubleVec;
#endif
class StMyAnalysisMaker : public StMaker {
	public:
		StMyAnalysisMaker(const char *name, StPicoDstMaker *picoMaker, const char *outName, int trigSelect);
		virtual ~StMyAnalysisMaker();

		bool isHT0_BBCMB_TOF0(StPicoEvent*, IntVec);
		bool isHT2_BBCMB(StPicoEvent*, IntVec);
		bool isGoodPartner(StPicoTrack*);
		bool isGoodTrack(StPicoTrack*);
		bool isEMCTrack(StPicoTrack*, StPicoBEmcPidTraits*);
		bool isSMDTrack(StPicoTrack*, StPicoBEmcPidTraits*);
		bool checkHotTower(int);
		void makerealevent();
		virtual int Init();
		virtual int Make();
		virtual int loopTrack();
		virtual void  Clear(Option_t *opt="");
		virtual int Finish();

		void    DeclareHistograms();
		void    WriteHistograms();

	private:
		StPicoDstMaker *mPicoDstMaker;
		StPicoDst      *mPicoDst;
		StPicoEvent    *event;
		TString    mOutName;
		int  mTrigSelect;

		int   mNBadRuns_HT0;
		int   mNBadRuns_HT2;
		IntVec  mTriggerIDs;

		TFile*   fout;
		float mHTth;
		float mHTAdc0th;
		float mHTAdc0thSys;
		float mEmcPtth;
		float MassE;
		float VzCut;
		float VzDiff;
		int nFPtsCutPart;
		int nFPtsCut;
		int nFPtsCutSys;
		int ndEdxPtsCut;
		int ndEdxPtsCutSys;
		float PtsRMin;
		float PtsRMax;
		float minPtCut;
		float dcaCut;
		float dcaCutSys;
		float TPCFR;
		float EtaCut;
		float PoeMin;
		float PoeMinSys;
		float PoeMax;
		float DistZ;
		float DistPhi;
		int NEta;
		int NPhi;
		float PairDiffMax;
		float PairDiffMin;
		float CurrentEvent_bField;
		int   CurrentEvent_nEs;
		int   CurrentEvent_nEMCE;
		int      CurrentEvent_EId[2000];
		int      CurrentEvent_ECharge[2000];
		int      CurrentEvent_ENhitsFit[2000];
		int      CurrentEvent_ENhitsDedx[2000];
		float    CurrentEvent_EDca[2000];
		float    CurrentEvent_ETOWE[2000];
		float    CurrentEvent_ETOWpovere[2000];
		float    CurrentEvent_EDistZ[2000];
		float    CurrentEvent_EDistPhi[2000];
		int      CurrentEvent_ESMDNEta[2000];
		int      CurrentEvent_ESMDNPhi[2000];
		//float    CurrentEvent_ENSigE[2000];
		//float    CurrentEvent_ETofBeta[2000];
		//float    CurrentEvent_EGpTPartner[2000];
		float    CurrentEvent_EPt[2000];
		float    CurrentEvent_EEta[2000];
		//float    CurrentEvent_EPhi[2000];
		float    CurrentEvent_EHelixPx[2000];
		float    CurrentEvent_EHelixPy[2000];
		float    CurrentEvent_EHelixPz[2000];
		float    CurrentEvent_EHelixX[2000];
		float    CurrentEvent_EHelixY[2000];
		float    CurrentEvent_EHelixZ[2000];
		//int      CurrentEvent_ETOWId[2000];

		int      CurrentEvent_EMCEId[2000];
		int      CurrentEvent_EMCECharge[2000];
		int      CurrentEvent_EMCENhitsFit[2000];
		int      CurrentEvent_EMCENhitsDedx[2000];
		float    CurrentEvent_EMCEDca[2000];
		//float    CurrentEvent_EMCENSigE[1000];
		//float    CurrentEvent_EMCETofMatchFlag[2000];
		//float    CurrentEvent_EMCETofYLocal[2000];
		float    CurrentEvent_EMCEPt[2000];
		//float    CurrentEvent_EMCEEta[2000];
		//float    CurrentEvent_EMCEPhi[2000];
		float    CurrentEvent_EMCEHelixPx[2000];
		float    CurrentEvent_EMCEHelixPy[2000];
		float    CurrentEvent_EMCEHelixPz[2000];
		float    CurrentEvent_EMCEHelixX[2000];
		float    CurrentEvent_EMCEHelixY[2000];
		float    CurrentEvent_EMCEHelixZ[2000];
		//float    CurrentEvent_EMCETofBeta[2000];
		//float    CurrentEvent_EMCEdEdx[2000];
		//float    CurrentEvent_EMCETOWE[2000];
		float    CurrentEvent_EMCETOWpovere[2000];
		float    CurrentEvent_EMCEDistZ[2000];
		float    CurrentEvent_EMCEDistPhi[2000];
		int      CurrentEvent_EMCESMDNEta[2000];
		int      CurrentEvent_EMCESMDNPhi[2000];
		int      CurrentEvent_EMCEDsmADC[2000];
		int      CurrentEvent_EMCEADC0[2000];
		float    CurrentEvent_EMCENSigE[2000];
		//int      CurrentEvent_EMCETOWId[2000];

		TH1F *hnEvent;
		TH2F *hVpdVz;
		TH2F *hVpdVzcut;
		TH1F *hVzDiff;
		//TH1F *hVzDiffGood;
		//TH2F *hBTOWERid;
		TH1F *hBTOWERid;
		TH2F *hAdc0;
		TH2F *hdsmAdc;
		TH2F *hAdc0vsdsmAdc;
		TH2F *hNSigE;
		TH2F *hNSigEPt;
		TH2F *hNSigEPtAdc0;
		TH2F *hNSigEPtnHitsFit;
		TH2F *hNSigEPtnHitsDedx;
		TH2F *hNSigEPtDca;
		TH2F *hNSigEPtEMCpovere;
		TH2F *hNSigESMD;
		TH2F *hNSigEPtSMD;
		TH2F *hNSigEPtAdc0SMD;
		TH2F *hNSigEPtnHitsFitSMD;
		TH2F *hNSigEPtnHitsDedxSMD;
		TH2F *hNSigEPtDcaSMD;
		TH2F *hNSigEPtEMCpovereSMD;
		TH2F *hAdc0Cut;
		TH2F *hdsmAdcCut;
		TH2F *hAdc0vsdsmAdcCut;
		TH2F *hAdc0CutSMD;
		TH2F *hdsmAdcCutSMD;
		TH2F *hAdc0vsdsmAdcCutSMD;
		TH2F *hnE;
		TH2F *hmvspt;
		TH2F *hmvsptlike;
		TH2F *hmvsptAdc0;
		TH2F *hmvsptAdc0like;
		TH2F *hmvsptnHitsFit;
		TH2F *hmvsptnHitsFitlike;
		TH2F *hmvsptnHitsDedx;
		TH2F *hmvsptnHitsDedxlike;
		TH2F *hmvsptDca;
		TH2F *hmvsptDcalike;
		TH2F *hmvsptEMCpovere;
		TH2F *hmvsptEMCpoverelike;
		TH2F *hmvsptSMD;
		TH2F *hmvsptSMDlike;
		TH2F *hmvsptAdc0SMD;
		TH2F *hmvsptAdc0SMDlike;
		TH2F *hmvsptnHitsFitSMD;
		TH2F *hmvsptnHitsFitSMDlike;
		TH2F *hmvsptnHitsDedxSMD;
		TH2F *hmvsptnHitsDedxSMDlike;
		TH2F *hmvsptDcaSMD;
		TH2F *hmvsptDcaSMDlike;
		TH2F *hmvsptEMCpovereSMD;
		TH2F *hmvsptEMCpovereSMDlike;
		TH2F *hAdc0PHE;
		TH2F *hAdc0PHElike;
		TH2F *hnHitsFit;
		TH2F *hnHitsFitlike;
		TH2F *hnHitsDedx;
		TH2F *hnHitsDedxlike;
		TH2F *hDca;
		TH2F *hDcalike;
		TH2F *hAdc0PHESMD;
		TH2F *hAdc0PHESMDlike;
		TH2F *hnHitsFitSMD;
		TH2F *hnHitsFitSMDlike;
		TH2F *hnHitsDedxSMD;
		TH2F *hnHitsDedxSMDlike;
		TH2F *hDcaSMD;
		TH2F *hDcaSMDlike;
		TH2F *hNSigEeff;
		TH2F *hNSigEefflike;
		TH2F *hNSigEeffSMD;
		TH2F *hNSigEeffSMDlike;
		TH1F *hTPCtracksTag;
		TH1F *hTPCtracksTaglike;
		TH1F *hSMDtracksTag;
		TH1F *hSMDtracksTaglike;
		TH1F *hTPCtracks;
		TH1F *hTPCtrackslike;
		TH1F *hEMCmatchingtracks;
		TH1F *hEMCmatchingtrackslike;
		TH1F *hEMCtracks;
		TH1F *hEMCtrackslike;
		TH1F *hSMDmatchingtracks;
		TH1F *hSMDmatchingtrackslike;
		TH1F *hSMDtracks;
		TH1F *hSMDtrackslike;
		TH1F *hTPCtracksSMD;
		TH1F *hTPCtracksSMDlike;
		TH1F *hEMCmatchingtracksSMD;
		TH1F *hEMCmatchingtracksSMDlike;
		TH1F *hEMCtracksSMD;
		TH1F *hEMCtracksSMDlike;
		TH1F *hSMDmatchingtracksSMD;
		TH1F *hSMDmatchingtracksSMDlike;
		TH1F *hSMDtracksSMD;
		TH1F *hSMDtracksSMDlike;
		ClassDef(StMyAnalysisMaker, 1)
};
#endif
