root -b -q -l  systematicsMinuit.C\(\"May5\",\"default\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"pileup\",kTRUE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"fitrange\",kFALSE,kFALSE,kTRUE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"purity\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"nsigmae\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"poe\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"rec\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"gpt\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"gpt04\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"masscut\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"trig\",kFALSE,kFALSE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"pythia\",kFALSE,kTRUE,kFALSE,kFALSE\)
root -b -q -l  systematicsMinuit.C\(\"May5\",\"jpsi\",kFALSE,kTRUE,kFALSE,kFALSE,kTRUE\)

